
# Application image
image:
  # Docker registry
  registry: "k3d-registry:5000"
  # Docker repository (application name)
  repository: "demo-quarkus"
  # Docker image tag (application version)
  tag: "latest"

# Number of replicas       
replicas: 1

# Livess probe
livenessProbe:
  url: /q/health/live

# Readines probe  
readinessProbe:
  url: /q/health/ready

# Pod configuration
pod:
  port: 8080

# Service configuration
service:
  port: 8080
     
# Ingress configuration
ingress:
  host: "demo-quarkus.localhost" 
